name: var output
on:
  workflow_dispatch: # manual trigger
jobs:
  Test-job:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.var.outputs.sum }}
    steps:
      - name: step
        id: var
        run: |
          echo "sum=10" >> "$GITHUB_OUTPUT"

      - name: print repo var
        run: |
          echo "${{ steps.var.outputs.sum }}"

  Production-job:
    needs: Test-job
    runs-on: ubuntu-latest
    steps:
      - name: print var
        run: |
          echo "${{ needs.Test-job.outputs.out }}"

          
      
