name: var output
on:
  workflow_dispatch: # manual trigger
jobs:
  Test-job:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.var.outputs.sum }}
    steps:
      - name: step
        id: var
        run: |
          echo "sum=10" >> "$GITHUB_ENV"

      - name: print repo var
        run: |
          echo "$GITHUB_REPOSITORY"
