name: PARENT
on:
  workflow_dispatch: # manual trigger
jobs:
  Test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: trigger child workflow
        uses: ./.github/workflows/child.yaml@main



          
