name: PARENT
on:
  workflow_dispatch: # manual trigger
jobs:
  Test-job:
    runs-on: ubuntu-latest
    steps:
      - name: print repo var
        run: |
          echo "$GITHUB_REPOSITORY"

      - name: checkout repo
        uses: actions/checkout@v3

      - name: trigger child workflow
        uses: ./.github/workflows/child.yaml@main


          
