name: print name
on:
  workflow_dispatch: # manual trigger
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      USER: shamsoddin
    steps:
      - name: print present working dir
        run: |
          echo "$USER"
          echo "${{ env.USER }}" # recommended way
          
          
