name: print name
on:
  workflow_dispatch: # manual trigger
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "${{ secrets.USERNAME }}"

      - name: print repo var
        run: |
          echo "${{ vars.TOKEN }}"

  Production:
    runs-on: ubuntu-latest
    steps:
      - name: print environment secret
        run: |
          echo "${{ secrets.PROD_TOKEN }}" 

      - name: env var
        run: |
          echo "${{ vars.ENV_TOKEN }}"


          
      
