name: print name
on:
  workflow_dispatch: # manual trigger
env:
  USERNAME: shamsoddin
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: print present working dir
        run: |
          echo "${{ env.USERNAME }}" # recommended way

      - name: step
        env:
          PASS: 1234
        run: |
          echo "${{ env.PASS }}
          
          

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: |
          echo "${{ env.USERNAME }}"
          
          
          
          
