name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona


      - name: print var name
        run: |
          echo "$First_Name"  
          echo "Today is $DAY_OF_WEEK!"
          echo "${{ env.DAY_OF_WEEK }}"

